# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development_mysql2:
  adapter: mysql2
  encoding: utf8
  database: Casamasomenos
  pool: 5
  username: root
  password: 

development:
  adapter: postgresql
  encoding: unicode
  database: Casamasomenos
  pool: 5
  username: Dani
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Casamasomenos_test
  pool: 5
  username: Dani
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Casamasomenos
  pool: 5
  username: postgres
  password: db4root
  host: localhost
